### ISSUE TITLE
Question about VCS and UVM

### ISSUE THREAD

**Issue by mikeurbach** [Kuree/hgdb#36]
Hi @Kuree, I have been trying to run hgdb with VCS and having some troubles. I want to make sure I'm using it right.

For one, the docs mention to invoke the `vcs` command with `-debug_acc+all -load libhgdb.so`. I'm not sure if that works as expected. I got the following error:

```
Warning-[RT_UO] Unsupported option
  Unsupported option '-debug_acc+all' is ignored
```

I also got an error related to `-load libhgdb.so`:

```
/usr/bin/ld: cannot find -load
collect2: error: ld returned 1 exit status
```

I tested this with version `Q-2020.03-SP2-4`. So, I removed that `-debug_acc+all` as well as `-load`, but at runtime, the debugger never seems to start and block the simulator. I'm running with `+DEBUG_LOG`, but nothing prints out. The simulation just runs to completion. I may be able to test with other simulators, but I was hoping to get VCS working.

I should note that I also tried a more recent version of VCS, but I picked that specific version because of this comment: https://github.com/Kuree/hgdb/blob/8a028b9ee8751a2cc77cd1c889e96059747b2f18/src/sim.cc#L55-L68

In both versions, the debugger never starts.

This may be because this internal test uses UVM and some other DPI features. I'm wondering if maybe that is conflicting with HGDB. I'm not an expert about DPI or VPI, but I can try to provide more information about the setup if it is relevant (or find an open source reproducer).

In the end, I am basically trying to get a demo working like the Rocket-Chip example you showed here: https://github.com/Kuree/hgdb-debugger. Do you have any docs or steps online to get the debugger running on a Rocket-Chip? If you can point me to which test you used, I will try debugging that myself.

**Comment by Kuree** [comment]
Here is the changes I made to the rocketchip make file. You should replace the shared library path with your local one.

```diff
diff --git a/vsim/Makefrag b/vsim/Makefrag
index 278384769..f5ba823db 100644
--- a/vsim/Makefrag
+++ b/vsim/Makefrag
@@ -48,6 +48,8 @@ VCS_OPTS = -notice -line +lint=all,noVCDE,noONGS,noUI -error=PCWM-L -timescale=1
        -CC "-Wl,-rpath,$(RISCV)/lib" \
        $(RISCV)/lib/libfesvr.a \
        -sverilog \
+    -debug_access+class \
+    -load /home/keyi/workspace/hgdb/cmake-build-release/src/libhgdb.so \
        +incdir+$(generated_dir) \
        +define+CLOCK_PERIOD=1.0 $(sim_vsrcs) $(sim_csrcs) \
        +define+PRINTF_COND=$(TB).printf_cond \
```

I used `class` instead of `all` since that's enough debug access for `hgdb`.

I'm using `Q-2020.03-SP2_Full64`, but I doubt that would make a difference.

`-debug_acc` or `-debug_access` are known switch to VCS. `-load` should be standard switch as well. You can do `vcs -h | less` to search `-load` and `debug_acc`. My guess is that VCS is not invoked properly given the error message you have.

> I should note that I also tried a more recent version of VCS, but I picked that specific version because of this comment:
I found out that VCS will run VPI initialization routine during the compilation. My guess is to detect which VPI hooks to compile into `simv` file. This however will trigger hgdb's built-in pause-on-startup behavior. So this detection is to bypass that. Once you run the `simv` file, it should just work properly.

**Comment by mikeurbach** [comment]
Hi @Kuree I was able to try this again, and it seems to be working well (note that I am not using remote debugging)! I must have screwed something up with how my build tool invoked vcs before. Thanks!
